### ISSUE TITLE
PhonemesService

### ISSUE THREAD

**Issue by navta** [davideberdin/Master-Thesis#15]
Hi,

Is there any guide on how to deploy the PhonemesService?
I have built the war file, but I'm new to tomcat and have been trying without success.

TIA

**Comment by spaghettifunk** [comment]
Hi,

When I developed the thing I encountered several problems as well and I did pretty much trial-and-error attempts. Although, at that time, I was using Ubuntu and I remember that I was uploading the WAR file to this directory `/var/lib/tomcat7/webapps` (or similar - depending on the Tomcat version you have) and then I was able to see the endpoint by going to the following address `http://server_name:8080/artifact/phonemes/transcription`. I can be mistaken but I guess I did in this way. Also, **server_name** was the actual IP address of the machine where I deployed the service.

I hope it helps

Davide

**Comment by navta** [comment]
It works now.

Thank you!
